find_package(CURL 7.85 REQUIRED)
find_package(Boost 1.70 REQUIRED COMPONENTS system)
find_package(SQLite3 REQUIRED)
find_package(Threads REQUIRED)
add_library(tes3mp-discovery STATIC Protocol.cpp Client.cpp)
target_include_directories(tes3mp-discovery PUBLIC ${CMAKE_SOURCE_DIR})
target_link_libraries(tes3mp-discovery PUBLIC tes3mp-security Boost::system CURL::libcurl Threads::Threads)
add_library(tes3mp-directory-core STATIC Directory.cpp Probe.cpp)
target_include_directories(tes3mp-directory-core PUBLIC ${CMAKE_SOURCE_DIR})
target_link_libraries(tes3mp-directory-core PUBLIC tes3mp-discovery tes3mp-game-endpoint SQLite::SQLite3)
if (MSVC)
    target_compile_options(tes3mp-discovery PRIVATE /W4 /WX)
    target_compile_options(tes3mp-directory-core PRIVATE /W4 /WX)
else()
    target_compile_options(tes3mp-discovery PRIVATE -Wall -Wextra -Wpedantic -Werror)
    target_compile_options(tes3mp-directory-core PRIVATE -Wall -Wextra -Wpedantic -Werror)
endif()
